import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { LanguageProvider } from "@/components/LanguageContext";
import { ThemeProvider } from "@/components/ThemeProvider";
import { SocketProvider } from "@/lib/socket";
import { ScreenShareProvider } from "@/components/ScreenShare";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <ThemeProvider>
          <SocketProvider>
            <ScreenShareProvider>
            <LanguageProvider>
              <div className="sticky top-0 z-90">
                <NavBar />
              </div>
              {children}
            </LanguageProvider>
            </ScreenShareProvider>
          </SocketProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
